In [2]:
# Libreria para mandejo de los dataset
import pandas as pd

In [4]:
# Dataset de la poblacion incluyendo una prediccion hasta 2100
poblacion = pd.read_csv("Dataset/Poblacion.csv")

In [5]:
poblacion.columns

Index(['Pais', 'Sexo', 'Anios', 'CantidadPoblacion'], dtype='object')

In [ ]:
# Revisamos los años filtrado por unique para que no se repitan 
poblacion['Anios'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032,
       2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043,
       2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054,
       2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065,
       2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076,
       2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087,
       2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098,
       2099, 2100])

In [ ]:
# Usaremos los años para nuetro análisis
poblacionF = poblacion[poblacion['Anios'].between(2015, 2100)].copy()

In [ ]:
# Revisamos el filtro
poblacionF['Anios'].unique()

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
       2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036,
       2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047,
       2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058,
       2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069,
       2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080,
       2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091,
       2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100])

In [ ]:
# Revismos los paises del dataset
poblacionF['Pais'].unique()

array(['Anguila', 'Antigua y Barbuda', 'Argentina', 'Aruba', 'Bahamas',
       'Barbados', 'Belice', 'Bolivia', 'Brasil', 'Caribe neerlandés',
       'Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Curaçao', 'Dominica',
       'Ecuador', 'El Salvador', 'Granada', 'Guadalupe', 'Guatemala',
       'Guyana', 'Haití', 'Honduras', 'Islas Caimán',
       'Islas Turcas y Caicos', 'Islas Vírgenes Británicas',
       'Islas Vírgenes de los Estados Unidos', 'Jamaica', 'Martinica',
       'México', 'Montserrat', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'Puerto Rico', 'República Dominicana', 'Saint Kitts y Nevis',
       'San Martín (parte de los Países Bajos)',
       'San Vicente y las Granadinas', 'Santa Lucía', 'Suriname',
       'Trinidad y Tabago', 'Uruguay', 'Venezuela',
       'América Latina y el Caribe', 'América Latina', 'El Caribe'],
      dtype=object)

In [ ]:
# 1. Creamos la lista con los paises que no nos sirven para este analisis
territorios_a_eliminar = [

    'Anguila', 'Islas Caimán', 'Islas Turcas y Caicos', 'Islas Vírgenes Británicas', 'Montserrat',
    
    'Guadalupe', 'Martinica', 
    
    'Aruba', 'Caribe neerlandés', 'Curaçao', 'San Martín (parte de los Países Bajos)',
    
    'Islas Vírgenes de los Estados Unidos', 'Puerto Rico',
    
    'América Latina y el Caribe', 'América Latina', 'El Caribe'
]

# 2. Aplicamos el filtro para que solo se quede con los paises utiles
poblacionF = poblacionF[~poblacionF['Pais'].isin(territorios_a_eliminar)].copy()


In [ ]:
# Revisamos el filtro
poblacionF['Pais'].unique()

array(['Antigua y Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belice',
       'Bolivia', 'Brasil', 'Chile', 'Colombia', 'Costa Rica', 'Cuba',
       'Dominica', 'Ecuador', 'El Salvador', 'Granada', 'Guatemala',
       'Guyana', 'Haití', 'Honduras', 'Jamaica', 'México', 'Nicaragua',
       'Panamá', 'Paraguay', 'Perú', 'República Dominicana',
       'Saint Kitts y Nevis', 'San Vicente y las Granadinas',
       'Santa Lucía', 'Suriname', 'Trinidad y Tabago', 'Uruguay',
       'Venezuela'], dtype=object)

In [14]:
poblacionF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5676 entries, 217 to 9291
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Pais               5676 non-null   object 
 1   Sexo               5676 non-null   object 
 2   Anios              5676 non-null   int64  
 3   CantidadPoblacion  5676 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 221.7+ KB


In [ ]:
# Dataset con puestos directivos ocupados con mujeres
puestosDir = pd.read_csv("Dataset/PuestosDirectivos.csv")

In [16]:
puestosDir.columns

Index(['Edad', 'Pais', 'Anio', 'Sexo', 'Porcentaje_Directivas'], dtype='object')

In [ ]:
# 1. Creamos la de las mismo forma que el pasado tomando en cuenta el dataset actual
territorios_a_eliminar_dir = [
    # Agrupaciones regionales (Macro regiones)
    'América Central', 
    'El Caribe', 
    'América Latina y el Caribe', 
    'América del Sur',
    
    # Territorios de ultramar y dependencias
    'Islas Caimán', 
    'Montserrat', 
    'Curaçao', 
    'Aruba', 
    'Puerto Rico', 
    'Anguila'
]

# 2. Aplicamos el filtro
puestosDir_limpio = puestosDir[~puestosDir['Pais'].isin(territorios_a_eliminar_dir)].copy()

# 3. Verificamos cómo quedó nuestra lista limpia
print(f"Total de países independientes: {len(puestosDir_limpio['Pais'].unique())}")
print(puestosDir_limpio['Pais'].unique())

array(['América Central', 'Islas Caimán', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Dominica', 'República Dominicana',
       'Ecuador', 'El Salvador', 'Antigua y Barbuda', 'El Caribe',
       'Granada', 'Argentina', 'Guatemala', 'Guyana', 'Haití', 'Honduras',
       'Jamaica', 'América Latina y el Caribe', 'Bahamas', 'México',
       'América del Sur', 'Montserrat', 'Barbados', 'Curaçao', 'Aruba',
       'Nicaragua', 'Panamá', 'Paraguay', 'Perú', 'Puerto Rico',
       'Anguila', 'Santa Lucía', 'San Vicente y las Granadinas',
       'Bolivia', 'Suriname', 'Brasil', 'Trinidad y Tabago', 'Belice',
       'Uruguay', 'Venezuela'], dtype=object)

In [ ]:
# 1. Creamos la la lista limía
territorios_a_eliminar_dir = [
    
    'América Central', 
    'El Caribe', 
    'América Latina y el Caribe', 
    'América del Sur',
    
    
    'Islas Caimán', 
    'Montserrat', 
    'Curaçao', 
    'Aruba', 
    'Puerto Rico', 
    'Anguila'
]

# limpiamos los paises
puestosDirF = puestosDir[~puestosDir['Pais'].isin(territorios_a_eliminar_dir)].copy()


In [ ]:
# Comprobamos el filtro
puestosDirF['Pais'].unique()

array(['Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Dominica',
       'República Dominicana', 'Ecuador', 'El Salvador',
       'Antigua y Barbuda', 'Granada', 'Argentina', 'Guatemala', 'Guyana',
       'Haití', 'Honduras', 'Jamaica', 'Bahamas', 'México', 'Barbados',
       'Nicaragua', 'Panamá', 'Paraguay', 'Perú', 'Santa Lucía',
       'San Vicente y las Granadinas', 'Bolivia', 'Suriname', 'Brasil',
       'Trinidad y Tabago', 'Belice', 'Uruguay', 'Venezuela'],
      dtype=object)

In [ ]:
# Ahora revisamos los años
puestosDirF['Anio'].unique()

array([2000, 2002, 2003, 2006, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2004, 2005,
       2007, 2008, 2001])

In [ ]:
# Aplicamos el filtro
puestosDirF = puestosDirF[puestosDirF['Anio'].between(2015, 2024)].copy()

In [ ]:
# Revisamos el Filtro
puestosDirF['Anio'].unique()

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [25]:
puestosDir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Edad                   580 non-null    object 
 1   Pais                   580 non-null    object 
 2   Anio                   580 non-null    int64  
 3   Sexo                   580 non-null    object 
 4   Porcentaje_Directivas  580 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 22.8+ KB


In [ ]:
# Dataset del pbi por paises
pbi = pd.read_csv('Dataset/dataPBI.csv')

In [28]:
pbi.columns

Index(['Pais', 'Anios', 'tasaCrecimiento'], dtype='object')

In [ ]:
# Revisamos los años del data set
pbi['Anios'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024])

In [ ]:
# Aplicamos filtro
pbiF = pbi[pbi['Anios'].between(2015, 2024)].copy()

In [ ]:
# Revisamos filtro
pbiF['Anios'].unique()

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [ ]:
# Ahora revisamos los paises
pbiF['Pais'].unique()

array(['América Central', 'Chile', 'Colombia', 'Costa Rica', 'Cuba',
       'República Dominicana', 'Ecuador', 'El Salvador', 'Haití',
       'Honduras', 'Jamaica', 'América Latina y el Caribe', 'El Caribe',
       'Argentina', 'Guatemala', 'Guyana', 'Bahamas', 'México',
       'América del Sur', 'Barbados', 'Nicaragua', 'Panamá', 'Paraguay',
       'Perú', 'Puerto Rico', 'Santa Lucía',
       'San Vicente y las Granadinas', 'Bolivia', 'Suriname', 'Brasil',
       'Trinidad y Tabago', 'Belice',
       'Islas Vírgenes de los Estados Unidos', 'Uruguay', 'Venezuela'],
      dtype=object)

In [ ]:
# 1. Definimos la lista 
territorios_a_eliminar_pbi = [
    
    'América Central', 
    'América Latina y el Caribe', 
    'El Caribe', 
    'América del Sur',
    
    'Puerto Rico', 
    'Islas Vírgenes de los Estados Unidos'
]

pbiF = pbiF[~pbiF['Pais'].isin(territorios_a_eliminar_pbi)].copy()



In [ ]:
# Revisamos el Filtro
pbiF['Pais'].unique()

array(['Chile', 'Colombia', 'Costa Rica', 'Cuba', 'República Dominicana',
       'Ecuador', 'El Salvador', 'Haití', 'Honduras', 'Jamaica',
       'Argentina', 'Guatemala', 'Guyana', 'Bahamas', 'México',
       'Barbados', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'Santa Lucía', 'San Vicente y las Granadinas', 'Bolivia',
       'Suriname', 'Brasil', 'Trinidad y Tabago', 'Belice', 'Uruguay',
       'Venezuela'], dtype=object)

In [ ]:
# Matriculacion
matriculacion = pd.read_csv('Dataset/MatriculacionStem.csv')

In [ ]:
# Comunas del dataset
matriculacion.columns

Index(['indicatorId', 'geoUnit', 'year', 'famale', 'male'], dtype='object')

In [ ]:
# Revisamos los paises

matriculacion['geoUnit'].unique()

array(['ABW', 'ARG', 'BLZ', 'BRA', 'CHL', 'COL', 'CRI', 'CUB', 'DOM',
       'ECU', 'GRD', 'GTM', 'HND', 'LCA', 'MEX', 'NIC', 'PAN', 'PER',
       'PRI', 'SLV', 'SXM', 'TCA', 'TTO', 'URY', 'VGB'], dtype=object)

In [ ]:
# 1. Definimos la lista 
territorios_iso_a_eliminar = ['ABW', 'PRI', 'SXM', 'TCA', 'VGB']

# 2. Aplicamos el filtro 
matriculacionF = matriculacion[~matriculacion['geoUnit'].isin(territorios_iso_a_eliminar)].copy()


In [ ]:
# Revisamos el Filtro
matriculacionF['geoUnit'].unique()

array(['ARG', 'BLZ', 'BRA', 'CHL', 'COL', 'CRI', 'CUB', 'DOM', 'ECU',
       'GRD', 'GTM', 'HND', 'LCA', 'MEX', 'NIC', 'PAN', 'PER', 'SLV',
       'TTO', 'URY'], dtype=object)

In [ ]:
# Revisamo los años
matriculacionF['year'].unique()

array([2018, 2019, 2020, 2021, 2022, 2023, 2015, 2024, 2016, 2017])

In [44]:
matriculacionF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116 entries, 1 to 124
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   indicatorId  116 non-null    object 
 1   geoUnit      116 non-null    object 
 2   year         116 non-null    int64  
 3   famale       116 non-null    float64
 4   male         116 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 5.4+ KB


In [45]:
pbiF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290 entries, 40 to 874
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Pais             290 non-null    object 
 1   Anios            290 non-null    int64  
 2   tasaCrecimiento  290 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 9.1+ KB


In [46]:
puestosDirF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 186 entries, 43 to 579
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Edad                   186 non-null    object 
 1   Pais                   186 non-null    object 
 2   Anio                   186 non-null    int64  
 3   Sexo                   186 non-null    object 
 4   Porcentaje_Directivas  186 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 8.7+ KB


In [47]:
poblacionF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5676 entries, 217 to 9291
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Pais               5676 non-null   object 
 1   Sexo               5676 non-null   object 
 2   Anios              5676 non-null   int64  
 3   CantidadPoblacion  5676 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 221.7+ KB


In [ ]:
import pandas as pd

# PASO 1: CREAR EL TRADUCTOR ISO -> NOMBRE 
diccionario_iso = {
    'ARG': 'Argentina', 'BHS': 'Bahamas', 'BRB': 'Barbados', 'BLZ': 'Belice',
    'BOL': 'Bolivia', 'BRA': 'Brasil', 'CHL': 'Chile', 'COL': 'Colombia',
    'CRI': 'Costa Rica', 'CUB': 'Cuba', 'DOM': 'República Dominicana',
    'ECU': 'Ecuador', 'SLV': 'El Salvador', 'GRD': 'Granada', 'GTM': 'Guatemala',
    'GUY': 'Guyana', 'HTI': 'Haití', 'HND': 'Honduras', 'JAM': 'Jamaica',
    'MEX': 'México', 'NIC': 'Nicaragua', 'PAN': 'Panamá', 'PRY': 'Paraguay',
    'PER': 'Perú', 'LCA': 'Santa Lucía', 'VCT': 'San Vicente y las Granadinas',
    'SUR': 'Suriname', 'TTO': 'Trinidad y Tabago', 'URY': 'Uruguay', 'VEN': 'Venezuela'
}

# PASO 2: NORMALIZAR NOMBRES DE COLUMNAS
# Tabla 1: Matriculación
matriculacionF_norm = matriculacionF.copy()
# Traducimos el código ISO al nombre completo
matriculacionF_norm['Pais'] = matriculacionF_norm['geoUnit'].map(diccionario_iso)
matriculacionF_norm = matriculacionF_norm.rename(columns={'year': 'Anio', 'famale': 'Matricula_Mujeres', 'male': 'Matricula_Hombres'})
# Nos quedamos solo con las columnas útiles 
matriculacionF_norm = matriculacionF_norm[['Pais', 'Anio', 'Matricula_Mujeres', 'Matricula_Hombres']].dropna(subset=['Pais'])

# Tabla 2: PBI
pbiF_norm = pbiF.copy()
pbiF_norm = pbiF_norm.rename(columns={'Anios': 'Anio'})

# Tabla 3: Puestos Directivos
puestosDirF_norm = puestosDirF.copy()
puestosDirF_norm = puestosDirF_norm[['Pais', 'Anio', 'Porcentaje_Directivas']]

# Tabla 4: Población
poblacionF_norm = poblacionF.copy()
poblacionF_norm = poblacionF_norm.rename(columns={'Anios': 'Anio'})

pob_total = poblacionF_norm.groupby(['Pais', 'Anio'])['CantidadPoblacion'].sum().reset_index()


# PASO 3: (MERGE) 
# Unimos Matriculación con Población
df_final = pd.merge(matriculacionF_norm, pob_total, on=['Pais', 'Anio'], how='outer')

# Unimos con PBI
df_final = pd.merge(df_final, pbiF_norm, on=['Pais', 'Anio'], how='outer')

# Unimos con Puestos Directivos
df_final = pd.merge(df_final, puestosDirF_norm, on=['Pais', 'Anio'], how='outer')

# PASO 4: LIMPIEZA 
# 
df_final = df_final.sort_values(by=['Pais', 'Anio']).reset_index(drop=True)

# Veamos el resultado
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2838 entries, 0 to 2837
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Pais                   2838 non-null   object 
 1   Anio                   2838 non-null   int64  
 2   Matricula_Mujeres      116 non-null    float64
 3   Matricula_Hombres      116 non-null    float64
 4   CantidadPoblacion      2838 non-null   float64
 5   tasaCrecimiento        290 non-null    float64
 6   Porcentaje_Directivas  186 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 155.3+ KB


In [ ]:
# Compramos los años
df_final['Anio'].unique()           

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
       2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036,
       2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047,
       2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058,
       2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069,
       2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080,
       2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091,
       2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100])

In [ ]:
# Compramos los años revisamos los valores
df_final.notnull().count()

Pais                     2838
Anio                     2838
Matricula_Mujeres        2838
Matricula_Hombres        2838
CantidadPoblacion        2838
tasaCrecimiento          2838
Porcentaje_Directivas    2838
dtype: int64

In [ ]:
import plotly.express as px

# Seleccionamos SOLO las columnas numéricas para nuestro modelo
columnas_modelo = [
    'CantidadPoblacion', 
    'tasaCrecimiento',       
    'Matricula_Mujeres', 
    'Matricula_Hombres', 
    'Porcentaje_Directivas'
]

# 2. Calculamos la matriz de correlación 
matriz_corr = df_final[columnas_modelo].corr().round(2)

# 3. Visualizamos la matriz 
fig = px.imshow(
    matriz_corr,
    text_auto=True,          
    aspect="auto",
    color_continuous_scale='RdBu_r', 
    title="Mapa de Calor: Correlación del Ecosistema STEM y Socioeconómico",
    labels=dict(color="Índice de Correlación")
)

fig.update_xaxes(side="bottom")
fig.show()


print("--- Tabla de Correlaciones ---")
print(matriz_corr)

--- Tabla de Correlaciones ---
                       CantidadPoblacion  tasaCrecimiento  Matricula_Mujeres  \
CantidadPoblacion                   1.00            -0.08              -0.10   
tasaCrecimiento                    -0.08             1.00              -0.02   
Matricula_Mujeres                  -0.10            -0.02               1.00   
Matricula_Hombres                   0.10             0.02              -1.00   
Porcentaje_Directivas              -0.19             0.09               0.32   

                       Matricula_Hombres  Porcentaje_Directivas  
CantidadPoblacion                   0.10                  -0.19  
tasaCrecimiento                     0.02                   0.09  
Matricula_Mujeres                  -1.00                   0.32  
Matricula_Hombres                   1.00                  -0.32  
Porcentaje_Directivas              -0.32                   1.00  


In [ ]:
from sklearn.linear_model import Ridge
import pandas as pd
import numpy as np

print("Iniciando la simulación del futuro (hasta 2100)...")

# 1. Definimos las variables de entrada 
features = ['Anio', 'CantidadPoblacion']
targets = ['Matricula_Mujeres', 'tasaCrecimiento', 'Porcentaje_Directivas']

# Lista para guardar los datos procesados de todos los países
predicciones_totales = []

# 2. Obtenemos la lista de países únicos
paises = df_final['Pais'].dropna().unique()

for pais in paises:
    # Aislamos los datos del país actual
    df_pais = df_final[df_final['Pais'] == pais].copy()
    
    # Separamos el PASADO (datos históricos reales para entrenar)
    df_train = df_pais.dropna(subset=['Matricula_Mujeres', 'Porcentaje_Directivas', 'tasaCrecimiento'])
    
    # Separamos el FUTURO (años donde tenemos población proyectada pero nos faltan los porcentajes)
    df_future = df_pais[df_pais['Matricula_Mujeres'].isna() & df_pais['CantidadPoblacion'].notna()].copy()
    
    # Si un país no tiene suficientes datos históricos (mínimo 3 años), lo guardamos como está y lo saltamos
    if len(df_train) < 3 or len(df_future) == 0:
        # Etiquetamos lo que haya como Histórico
        if len(df_train) > 0:
            df_pais['Tipo_Dato'] = 'Histórico'
        predicciones_totales.append(df_pais) 
        continue
        
    # --- ENTRENAMIENTO Y PREDICCIÓN 
    for target in targets:
        # Iniciamos el motor Lineal con Regularización (Ridge)
        ridge_model = Ridge(alpha=1.0) 
        
    
        X_train = df_train[features]
        y_train = df_train[target]
        
        # Entrenamos el modelo 
        ridge_model.fit(X_train, y_train)
        
        # Predecimos el futuro
        X_future = df_future[features]
        prediccion_cruda = ridge_model.predict(X_future)
        
        # Limitamos porcentajes entre 0 y 100
        if target in ['Matricula_Mujeres', 'Porcentaje_Directivas']:
            df_future[target] = np.clip(prediccion_cruda, 0, 100)
        else:
            # Para la tasa de crecimiento 
            df_future[target] = prediccion_cruda
    
    # Calculamos a los Hombres automáticamente 
    df_future['Matricula_Hombres'] = 100 - df_future['Matricula_Mujeres']
    
    # Etiquetamos visualmente qué es real y qué es simulado
    df_train['Tipo_Dato'] = 'Histórico'
    df_future['Tipo_Dato'] = 'Predicción'
    
    # Unimos el pasado real con el futuro predicho para este país
    df_pais_completo = pd.concat([df_train, df_future]).sort_values('Anio')
    
    # Lo agregamos a la lista maestra
    predicciones_totales.append(df_pais_completo)


df_prediccion_final = pd.concat(predicciones_totales)

# Redondeamos los números
df_prediccion_final = df_prediccion_final.round(2)

# Exportamos el JSON
nombre_archivo = 'prediccion_filtro_invisible_2100.json'
df_prediccion_final.to_json(nombre_archivo, orient='records')

print(f"¡Simulación terminada con éxito! Archivo '{nombre_archivo}' generado y listo para React.")

Iniciando la simulación del futuro (hasta 2100)...


C:\Users\gerar\AppData\Local\Temp\ipykernel_6184\2404676301.py:62: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gerar\AppData\Local\Temp\ipykernel_6184\2404676301.py:62: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gerar\AppData\Local\Temp\ipykernel_6184\2404676301.py:62: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/panda

¡Simulación terminada con éxito! Archivo 'prediccion_filtro_invisible_2100.json' generado y listo para React.


In [ ]:
import plotly.graph_objects as go
import pandas as pd

# 1. Filtramos solo los datos de México
df_mexico = df_prediccion_final[df_prediccion_final['Pais'] == 'México'].copy()

# 2. Separamos el pasado del futuro para darles estilos diferentes
df_historico = df_mexico[df_mexico['Tipo_Dato'] == 'Histórico']
df_prediccion = df_mexico[df_mexico['Tipo_Dato'] == 'Predicción']

# Copiamos el último año histórico y lo pegamos al inicio de la predicción.
ultimo_historico = df_historico.iloc[-1:]
df_prediccion_conectada = pd.concat([ultimo_historico, df_prediccion])

# 3. Iniciamos el lienzo 
fig = go.Figure()

# --- LÍNEAS DE MATRÍCULA STEM  ---
# Pasado (Sólido)
fig.add_trace(go.Scatter(
    x=df_historico['Anio'], y=df_historico['Matricula_Mujeres'],
    mode='lines', name='Matrícula STEM (Real)', 
    line=dict(color='#ec4899', width=3)
))
# Futuro (Punteado)
fig.add_trace(go.Scatter(
    x=df_prediccion_conectada['Anio'], y=df_prediccion_conectada['Matricula_Mujeres'],
    mode='lines', name='Matrícula STEM (IA)', 
    line=dict(color='#ec4899', width=3, dash='dash')
))

# --- LÍNEAS DE PUESTOS DIRECTIVOS (Color Morado) ---
# Pasado (Sólido)
fig.add_trace(go.Scatter(
    x=df_historico['Anio'], y=df_historico['Porcentaje_Directivas'],
    mode='lines', name='Directivas (Real)', 
    line=dict(color='#9333ea', width=3)
))
# Futuro (Punteado)
fig.add_trace(go.Scatter(
    x=df_prediccion_conectada['Anio'], y=df_prediccion_conectada['Porcentaje_Directivas'],
    mode='lines', name='Directivas (IA)', 
    line=dict(color='#9333ea', width=3, dash='dash')
))

# 4. Agregamos la línea vertical divisoria del "Presente"
# Tomamos el último año histórico como el punto de corte
año_corte = df_historico['Anio'].max()
fig.add_vline(x=año_corte, line_width=2, line_dash="dot", line_color="slateGray",
              annotation_text="← Pasado | Predicción IA →", annotation_position="top right")

# 5. Diseño y estética
fig.update_layout(
    title="Trayectoria de Mujeres en STEM (México)",
    xaxis_title="Año",
    yaxis_title="Porcentaje (%)",
    yaxis=dict(range=[0, 100]), #  mostrar de 0 a 100%
    template="plotly_white",
    hovermode="x unified" # Muestra todos los datos de un año al pasar el mouse
)

fig.show()

In [ ]:
import plotly.graph_objects as go
import pandas as pd

# 1. Filtramos solo los datos de Argentina
df_mexico = df_prediccion_final[df_prediccion_final['Pais'] == 'Argentina'].copy()


df_historico = df_mexico[df_mexico['Tipo_Dato'] == 'Histórico']
df_prediccion = df_mexico[df_mexico['Tipo_Dato'] == 'Predicción']


ultimo_historico = df_historico.iloc[-1:]
df_prediccion_conectada = pd.concat([ultimo_historico, df_prediccion])


fig = go.Figure()


fig.add_trace(go.Scatter(
    x=df_historico['Anio'], y=df_historico['Matricula_Mujeres'],
    mode='lines', name='Matrícula STEM (Real)', 
    line=dict(color='#ec4899', width=3)
))

fig.add_trace(go.Scatter(
    x=df_prediccion_conectada['Anio'], y=df_prediccion_conectada['Matricula_Mujeres'],
    mode='lines', name='Matrícula STEM (IA)', 
    line=dict(color='#ec4899', width=3, dash='dash')
))

fig.add_trace(go.Scatter(
    x=df_historico['Anio'], y=df_historico['Porcentaje_Directivas'],
    mode='lines', name='Directivas (Real)', 
    line=dict(color='#9333ea', width=3)
))

fig.add_trace(go.Scatter(
    x=df_prediccion_conectada['Anio'], y=df_prediccion_conectada['Porcentaje_Directivas'],
    mode='lines', name='Directivas (IA)', 
    line=dict(color='#9333ea', width=3, dash='dash')
))


año_corte = df_historico['Anio'].max()
fig.add_vline(x=año_corte, line_width=2, line_dash="dot", line_color="slateGray",
              annotation_text="← Pasado | Predicción IA →", annotation_position="top right")


fig.update_layout(
    title="Trayectoria de Mujeres en STEM (Argentina)",
    xaxis_title="Año",
    yaxis_title="Porcentaje (%)",
    yaxis=dict(range=[0, 100]), 
    template="plotly_white",
    hovermode="x unified" 
)

fig.show()

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import Ridge
import pandas as pd

# 1. Creamos una lista 
resultados_evaluacion = []

# 2. Iteramos sobre todos los países
paises = df_final['Pais'].dropna().unique()
features = ['Anio', 'CantidadPoblacion']

for pais in paises:
    # Aislamos el pasado histórico del país
    df_pais = df_final[df_final['Pais'] == pais].dropna(subset=['Matricula_Mujeres', 'Porcentaje_Directivas'])
    
    # Exigimos al menos 3 años de datos para que la métrica 
    if len(df_pais) < 3:
        continue
        
    X_real = df_pais[features]
    y_matricula = df_pais['Matricula_Mujeres']
    y_directivas = df_pais['Porcentaje_Directivas']
    
    # 3. Entrenamos modelos rápidos para evaluar
    modelo_mat = Ridge(alpha=1.0).fit(X_real, y_matricula)
    modelo_dir = Ridge(alpha=1.0).fit(X_real, y_directivas)
    
    pred_mat = modelo_mat.predict(X_real)
    pred_dir = modelo_dir.predict(X_real)
    
    # 4. Calculamos las métricas 
    r2_mat = r2_score(y_matricula, pred_mat)
    mae_mat = mean_absolute_error(y_matricula, pred_mat)
    
    r2_dir = r2_score(y_directivas, pred_dir)
    mae_dir = mean_absolute_error(y_directivas, pred_dir)
    
    # Guardamos los resultados
    resultados_evaluacion.append({
        'Pais': pais,
        'R2_Matricula': round(r2_mat, 2),
        'MAE_Mat_Puntos_Porcentuales': round(mae_mat, 2),
        'R2_Directivas': round(r2_dir, 2),
        'MAE_Dir_Puntos_Porcentuales': round(mae_dir, 2)
    })

# 5. Convertimos a tabla y la ordenamos 
df_metricas = pd.DataFrame(resultados_evaluacion)
df_metricas = df_metricas.sort_values(by='R2_Matricula', ascending=False).reset_index(drop=True)

# Imprimimos la tabla
print("--- Resultado del Modelo Ridge por País ---")
print(df_metricas.to_string())

--- Auditoría del Modelo Ridge por País ---
                    Pais  R2_Matricula  MAE_Mat_Puntos_Porcentuales  R2_Directivas  MAE_Dir_Puntos_Porcentuales
0                  Chile          0.90                         0.24           0.40                         0.95
1                 Brasil          0.81                         0.63           0.32                         0.50
2                 México          0.80                         0.50           0.76                         0.45
3      Trinidad y Tabago          0.78                         0.54           0.54                         0.67
4               Colombia          0.74                         0.42           0.63                         1.54
5             Costa Rica          0.72                         0.64           0.55                         3.78
6                 Panamá          0.70                         1.54           0.12                         2.17
7            El Salvador          0.63                      